services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 5
    env_file:
      - ./.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432
  # keycloak:
  #   image: quay.io/keycloak/keycloak:latest
  #   command: start-dev
  #   environment:
  #     - KC_BOOTSTRAP_ADMIN_USERNAME=admin
  #     - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
  #   ports:
  #     - "8081:8080"

volumes:
  postgres-data:
