services:
  postgres:
    image: postgres:17.5
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pg_isready -U $$DB_USER -d ${BD_NAME}"]
      interval: 30s
      timeout: 10s
      retries: 5
    environment:
      POSTGRES_USER: ${BD_USER}
      POSTGRES_PASSWORD: ${BD_PASSWORD}
      POSTGRES_DB: ${BD_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5434:5432

volumes:
  postgres-data:
