spring:
  application:
    name: meo
  config:
    import: file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5434/${BD_NAME}
    username: ${BD_USER}
    password: ${BD_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
