spring:
  application:
    name: meo
  config:
    import: file:.env[.properties]
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
